name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Deploy HTML files to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: DISS
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        # Specify the path to your HTML files to deploy
        package: C:\Users\jjh\Documents\GitHub\DISS

    - name: Deploy PHP files to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: DISS
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        # Specify the path to your PHP files to deploy
        package: C:\xampp\htdocs
