name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Home&Login  # 사용 중인 브랜치 이름을 넣어주세요

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_WAVE_08298C000 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/"  # 프로젝트의 루트 디렉토리
        output_location: "/"  # 빌드 출력 디렉토리 (예: build 또는 dist)
